### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'CSRFPreventionToken')

### ISSUE THREAD

**Issue by Marco12223** [ttarvis/node-proxmox#10]
Wenn man versucht sich in ein Konto einzuloggen tritt dieser Fehler auf 

D:\Development\Phpstorm\pve-nvc-cmd-test\node_modules\proxmox\lib\proxmox.js:69
            token.CSRF = response.data.CSRFPreventionToken;
                                       ^

TypeError: Cannot read properties of null (reading 'CSRFPreventionToken')
    at D:\Development\Phpstorm\pve-nvc-cmd-test\node_modules\proxmox\lib\proxmox.js:69:33
    at D:\Development\Phpstorm\pve-nvc-cmd-test\node_modules\proxmox\lib\proxmox.js:58:9
    at ChildProcess.exithandler (node:child_process:390:7)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by KikyoC** [comment]
Hello, download the proxmox file, then under command = curlCom().post('/access/ticket',authString).command(); put this finalcommand= command.split("&").join("\" --data-urlencode \""); and replace     curl(command, function(err, response) { by     curl(finalcommand, function(err, response) {
