### ISSUE TITLE
CSRF

### ISSUE THREAD

**Issue by yoranjj** [ttarvis/node-proxmox#4]
TypeError: Cannot read property 'CSRFPreventionToken' of null
    at D:\Dev\Tide Hosting\node_modules\proxmox\lib\proxmox.js:69:32
    at D:\Dev\Tide Hosting\node_modules\proxmox\lib\proxmox.js:58:9
    at ChildProcess.exithandler (child_process.js:202:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

Interesting error, did I do something wrong?

**Comment by yoranjj** [comment]
Fixed.

**Comment by Yub0** [comment]
How did you fixed this problem ?
