### ISSUE TITLE
CSRF Error

### ISSUE THREAD

**Issue by Yub0** [ttarvis/node-proxmox#6]
/Users/yubo/Documents/api-prox-vz/node_modules/proxmox/lib/proxmox.js:68
	    token.CSRF = response.data.CSRFPreventionToken;
	                              ^

TypeError: Cannot read property 'CSRFPreventionToken' of null
    at /Users/yubo/Documents/api-prox-vz/node_modules/proxmox/lib/proxmox.js:68:32
    at /Users/yubo/Documents/api-prox-vz/node_modules/proxmox/lib/proxmox.js:57:9
    at ChildProcess.exithandler (child_process.js:195:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)

How I can fix that please ?

**Comment by Yub0** [comment]
up :(

**Comment by orlandogodoy** [comment]
I solved this fix add 

  var authString = 'username=' + name + '&password=' + pwd +'&realm=pam';

on Line 9, file proxmox.js 

I think the problem is the Proxmox's version
